image: node:lts-alpine

cache:
  paths:
    - node_modules/

stages:
  - test
  - audit

test:
  stage: test
  except:
  - schedules
  script:
    - yarn install
    - yarn test:ci
  coverage: '/^Statements\s*:\s*([^%]+)/'

audit:
  stage: audit
  only:
  - schedules
  script:
    - yarn audit
